config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "restaurants#index"
  
  put "/summary", :to=>"restaurants#summary"
  get "/summary", :to=>"restaurants#summary"
  put "/increaseUpvote", :to=>"restaurants#increaseUpvote"
  put "/increaseDownvote", :to=>"restaurants#increaseDownvote"
  
  get "/newComment", :to=>"restaurants#newComment"
  post "/newComment", :to=>"restaurants#addComment"
  post "/toggleFavorite", :to=>"restaurants#toggleFavorite"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  has_many :users, through: :reviews
  has_many :comments
  has_many :users, through: :comments
  has_many :favorites
  has_many :users, through: :favorites

  validates :name, presence: true
  validates :location, presence: true
  
  def self.search(query)
    if query
      self.where("location LIKE ? OR name LIKE ?", "%#{query}%", "%#{query}%")
    else
      @restaurants = Restaurant.all
    end
  end
  
  def self.showUpvote(id)
    @restaurantVotes = Review.where("restaurant_id == ?", id)
    tally = 0
    @restaurantVotes.each do |vote|
      tally = vote.upvote + tally
    end
    tally
  end

  def self.showDownvote(id)
    @restaurantVotes = Review.where("restaurant_id == ?", id)
    tally = 0
    @restaurantVotes.each do |vote|
      tally = vote.downvote + tally
    end
    tally
  end
  
  def self.isFavorite(current_user, id)
    @fave = Favorite.where("user_id == ? AND restaurant_id == ?", current_user, id)
    status = false
    @fave.each do |favorite|
      if favorite.isFavorite
        status = true
      end
    end
    status
  end
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :restaurants, through: :reviews
  has_many :comments
  has_many :restaurants, through: :comments
  has_many :favorites
  has_many :restaurants, through: :favorites

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, :except => [:index, :show]

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.search(params[:query])
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
    @comments = Comment.where("restaurant_id == ?", @restaurant)
    @fave = Favorite.where("user_id == ? AND restaurant_id == ?", current_user, @restaurant)
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def increaseUpvote
    @thisRestaurant = Restaurant.find(params[:id])
    @thisUser = current_user
    Review.create(restaurant: @thisRestaurant, user: @thisUser, upvote: 1, downvote: 0)
    redirect_to action: "index" 
  end

  def increaseDownvote
    @thisRestaurant = Restaurant.find(params[:id])
    @thisUser = current_user
    Review.create(restaurant: @thisRestaurant, user: @thisUser, upvote: 0, downvote: 1)
    redirect_to action: "index" 
  end
  
  def summary
    @comments = Comment.where("user_id == ?", current_user)
    @votes = Review.where("user_id == ?", current_user)
    @favorites = Favorite.where("user_id == ?", current_user)
  end
  
  def newComment
    @restaurant = Restaurant.find(params[:restaurant])
  end
  
  def addComment
    @thisRestaurant = Restaurant.find(params[:restaurant])
    @thisUser = current_user
    Comment.create(restaurant: @thisRestaurant, user: @thisUser, fullComment: params[:fullComment])
    respond_to do |format|
      format.html { redirect_to restaurant_url(@thisRestaurant), notice: "Comment successfully added." }
      format.json { head :no_content }
    end
  end
  
  def toggleFavorite
    @thisRestaurant = Restaurant.find(params[:restaurant])
    @thisUser = current_user
    begin
      Favorite.create(restaurant: @thisRestaurant, user: @thisUser, isFavorite: true)
    rescue ActiveRecord::RecordNotUnique => e
      @oldFavorite = Favorite.where("user_id == ? AND restaurant_id == ?", @thisUser, @thisRestaurant)
      @oldFavorite.each do |favorite|
        favorite.toggle!(:isFavorite)
      end
    end
    respond_to do |format|
      format.html { redirect_to restaurant_url(@thisRestaurant), notice: "Favorite changed." }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :location, :upvote, :downvote, :query)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SplitTheCheck</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="alert"><%= alert %></p>
    <div class="app-header">
      <h1>WILL THEY SPLIT?</h1>
      <h2>A Restaurant Voting Guide</h2>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SplitTheCheck</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="alert"><%= alert %></p>
    <div class="app-header">
      <h1>WILL THEY SPLIT?</h1>
      <h2>A Restaurant Voting Guide</h2>
    </div>
    <div class="devise-content">
    <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Restaurant Name" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="restaurant-form">

  <%= render 'form', restaurant: @restaurant %>

  <%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<div class="navigation-wrapper">
<% if user_signed_in? %>

  <div><%= link_to 'New Restaurant', new_restaurant_path %></div>
  <div>
  <%= form_with url: restaurants_path, method: :get do |form| %>
    <%= form.text_field :query %>
    <%= form.submit "Search" %>
  <% end %>
  </div>
  <div>
    Welcome <%= current_user.email %> || 
    <%= link_to 'Your Summary', summary_path, :method => :put  %> || 
    <%= link_to :logout, destroy_user_session_path, :method => :delete  %>
  </div>

<% else %>

  <div></div>
  <div>
  <%= form_with url: restaurants_path, method: :get do |form| %>
    <%= form.text_field :query %>
    <%= form.submit "Search" %>
  <% end %>
  </div>
  <div>
    <%= link_to 'Sign In', new_user_session_path %> || 
    <%= link_to 'New User', new_user_registration_path %>
  </div>

<% end %>
</div>

<% if user_signed_in? %>

<table class="index-table">
  <thead>
    <tr>
      <th>Restaurant Name</th>
      <th>Location</th>
      <th colspan="2">Vote Results</th>
      <th colspan="2">Vote!</th>
      <th colspan="2"></th>
    </tr>
    <tr>
      <th colspan="2"></th>
      <th>Up</th>
      <th>Down</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.location %></td>
        <td class="upvote"><%= Restaurant.showUpvote(restaurant.id) %></td>
        <td class="downvote"><%= Restaurant.showDownvote(restaurant.id) %></td>
        <td><%= button_to 'Will Split', increaseUpvote_path, method: :put, params: { id: restaurant.id } %></td>
        <td><%= button_to 'Won\'t Split', increaseDownvote_path, method: :put, params: { id: restaurant.id } %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>

<table class="index-table">
  <thead>
    <tr>
      <th>Restaurant Name</th>
      <th>Location</th>
      <th colspan="2">Vote Results</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.location %></td>
        <td class="upvote"><%= Restaurant.showUpvote(restaurant.id) %></td>
        <td class="downvote"><%= Restaurant.showDownvote(restaurant.id) %></td>
        <td><%= link_to 'Show', restaurant %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

<br>

app/views/restaurants/new.html.erb
<div class="restaurant-form">

  <%= render 'form', restaurant: @restaurant %>

  <%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/newComment.html.erb
<div class="restaurant-form">
<h1>Comment on <%= @restaurant.name %></h1>
<%= form_with model: @comment do |form| %>
  <div class="field">
  <%= form.text_area :fullComment, size: "60x10" %>
  </div>
  <%= form.hidden_field :restaurant, :value => @restaurant.id %>
  <div class="actions">
  <%= form.submit %>
  </div>
<% end %>

  <%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/search.html.erb
<p id="notice"><%= notice %></p>

<div class="navigation-wrapper">
  <div class="test"><%= link_to 'New Restaurant', new_restaurant_path %></div>
  <div class="test">
  <%= form_with url: restaurants_path, method: :get do |form| %>
    <%= form.text_field :query %>
    <%= form.submit "Search" %>
  <% end %>
  </div>
</div>

<table class="index-table">
  <thead>
    <tr>
      <th>Restaurant Name</th>
      <th>Location</th>
      <th colspan="2">Vote Results</th>
      <th colspan="2">Vote!</th>
      <th colspan="2"></th>
    </tr>
    <tr>
      <th colspan="2"></th>
      <th>Up</th>
      <th>Down</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.location %></td>
        <td><%= restaurant.upvote %></td>
        <td><%= restaurant.downvote %></td>
        <td><%= button_to 'Will Split', increaseUpvote_path, method: :put, params: { id: restaurant.id } %></td>
        <td><%= button_to 'Won\'t Split', increaseDownvote_path, method: :put, params: { id: restaurant.id } %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <% if user_signed_in? %>
    <% if Restaurant.isFavorite(current_user, @restaurant) %>
      <h2 class="link"><%= button_to 'Remove Favorite', toggleFavorite_path(:restaurant => @restaurant) %></h2>
    <% else %>
      <h2 class="link"><%= button_to 'Add Favorite', toggleFavorite_path(:restaurant => @restaurant) %></h2>
    <% end %>
  <% end %>
</div>

<div class="show-wrapper">
  <div class="show-info"><%= @restaurant.name %></div>
  <div class="show-info"><%= @restaurant.location %></div>
  <div>Upvotes</div>
  <div>Downvotes</div>
  <div class="votes"><%= Restaurant.showUpvote(@restaurant.id) %></div>
  <div class="votes"><%= Restaurant.showDownvote(@restaurant.id) %></div>
</div>

<div>
  <% if user_signed_in? %>
    <h2 class="link"><%= link_to 'Add Comment', newComment_path(:restaurant => @restaurant) %></h2>
  <% end %>
</div>

<table class="index-table">
  <thead>
    <tr>
      <th>Comments</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.fullComment %></td>
      </tr>
    <% end %>
  </tbody>
</table>




<div class="show-footer">
  <%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/summary.html.erb
<p id="notice"><%= notice %></p>

<div class="navigation-wrapper">
  <%= link_to 'Back', restaurants_path %>
</div>

<h1 class="summary">Your Comments</h1>
<table class="index-table">
  <thead>
    <tr>
      <th width="40%">Restaurant Name</th>
      <th width="50%">Comment</th>
      <th width="10%"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.restaurant.name %></td>
        <td><%= comment.fullComment %></td>
        <td><%= link_to 'Show', comment.restaurant %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1 class="summary">Your Favorites</h1>
<table class="index-table">
  <thead>
    <tr>
      <th width="90%">Restaurant Name</th>
      <th width="10%"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <% if favorite.isFavorite %>
        <tr>
          <td><%= favorite.restaurant.name %></td>
          <td><%= link_to 'Show', favorite.restaurant %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h1 class="summary">Your Votes</h1>
<table class="index-table">
  <thead>
    <tr>
      <th width="50%">Restaurant Name</th>
      <th width="20%">Will Votes</th>
      <th width="20%">Won't Votes</th>
      <th width="10%"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.restaurant.name %></td>
        <td><%= vote.upvote %></td>
        <td><%= vote.downvote %></td>
        <td><%= link_to 'Show', vote.restaurant %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>